# Generated by Django 3.1.8 on 2021-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
